micronaut:
  application:
    name: groovyDemo
  server:
    port: -1


---
micronaut:
  views:
    thymeleaf:
      enabled: true
---
micronaut:
  router:
    static-resources:
      default:
        mapping: "/**"
      '*':
        paths:
        - "classpath:static"